### ISSUE TITLE
Traduzir todos os módulos para o inglês

### ISSUE THREAD

**Issue by igorcaavalcante** [igorcaavalcante/easyru#4]
Use os nomes abaixo para cada classe:

Funcionario > Operator
Consumidor > Consumer
Gru > Gru
Transacao > Transaction

Lembrando que precisa traduzir também os atributos (campos)

**Comment by igorcaavalcante** [comment]
Use os nomes abaixo para cada classe:

Funcionario > Operator
Consumidor > Consumer
Gru > Gru
Transacao > Transaction

Lembrando que precisa traduzir também os atributos (campos)

**Comment by elioadriao** [comment]
Feito!
[Commit](https://github.com/igorcaavalcante/easyru/commit/64f68c51d1faaa7dcbd73ebf26de0779f4315e5a)
